services:
  - type: web
    name: library-springboot-api
    env: docker
    region: singapore
    plan: free
    repo: https://bitbucket.org/abbdlazizz/library
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.vvkiozfhafgtkpffupjo
      - key: SPRING_DATASOURCE_PASSWORD
        value: aztestproject123!
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none
