name: Deploy Spring Boot App to Alibaba ECS

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            pkill -f 'java -jar' || true
            cd ~/app
            rm -f app.jar
            exit || true

      - name: Upload new JAR
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          source: target/*.jar
          target: /home/${{ secrets.USERNAME }}/app/app.jar

      - name: Start App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            cd ~/app
            nohup java -jar app.jar > output.log 2>&1 &
