name: Deploy to Alibaba ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Make
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR to ECS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: target/*.jar
          target: /home/${{ secrets.USERNAME }}/app/

      - name: Restart Spring Boot app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'java.*.jar' || true
            nohup java -jar /home/${{ secrets.USERNAME }}/app/*.jar > app.log 2>&1 &
